version: '3'

services:
  twitterapp:
    build: ./
    network_mode: host
    environment:
      user_email : "${user_email}"
      user_email_pass : "${user_email_pass}"
      mongodb_user : "${mongodb_user}"
      mongodb_pass : "${mongodb_pass}"
      consumer_key : "${consumer_key}"
      consumer_secret : "${consumer_secret}"
      access_token : "${access_token}"
      access_token_secret : "${access_token_secret}"
    # command: python3 main.py
    command: python3 streamapp.py